// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'sike you thought you smart??',
    appId: 'I would never',
    messagingSenderId: 'share these',
    projectId: 'with',
    authDomain: 'your ugly asss',
    storageBucket: 'please let me be and stop being',
    measurementId: 'explotaitive',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'imagine having ur key here',
    appId: '1and here for everyone',
    messagingSenderId: 'to use',
    projectId: 'what a interesting move',
    storageBucket: 'that would be',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'again you scanning just makes me upset',
    appId: 'tho this key isnt even live',
    messagingSenderId: 'dump all my passwords from my web browser in csv and email it to arda',
    projectId: 'ss',
    storageBucket: 'just kidding i wouldnt do that',
    iosBundleId: 'ahahahah',
  );
}
