// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-JClruhaKNez4w-DyfZJnqxNvaki2zqI',
    appId: '1:377205896368:web:dad3df490c2b4cb04ab775',
    messagingSenderId: '377205896368',
    projectId: 'deeds-ee5db',
    authDomain: 'deeds-ee5db.firebaseapp.com',
    storageBucket: 'deeds-ee5db.firebasestorage.app',
    measurementId: 'G-X94MLJEHRG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZDWjDqsk3XinLviChH0p0KCqgZr7jEg',
    appId: '1:377205896368:android:65a9367d971f75134ab775',
    messagingSenderId: '377205896368',
    projectId: 'deeds-ee5db',
    storageBucket: 'deeds-ee5db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA78XHG1Dvepzp2dPrcZOrHrv96QMySCw8',
    appId: '1:377205896368:ios:eea7839956f7f4c84ab775',
    messagingSenderId: '377205896368',
    projectId: 'deeds-ee5db',
    storageBucket: 'deeds-ee5db.firebasestorage.app',
    iosBundleId: 'com.ah13.deeds',
  );
}
